### ISSUE TITLE
Why do I still receive "Could not do a head request, falling back to regular pull." ?

### ISSUE THREAD

**Issue by DannyBoyKN** [containrrr/watchtower#880]
**Environment**
 - Platform **Raspberry Pi 4**
 - Architecture **armv7l**
 - Docker version **Docker version 20.10.0, build 7287ab3**

Since a while I'm using watchtower to regularly update my containers, which was working fine. However, since some time I was getting the message "_Could not do a head request, falling back to regular pull._" at every watchtower re-run, at the beginning, when containers are going to be updated and even if nothing has to be done. I read somewhere that pulling too often from docker hub could cause that message, however since quite a while I reduced the update requests to daily, see docker-compose below.

The behavior can easily be reproduced by executing watchtower using the compose file below:
```
version: "3.6"
services:
  watchtower:
    image: containrrr/watchtower:armhf-latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - "WATCHTOWER_NOTIFICATION_URL=pushover://shoutrrr:<devicetag>@<usertag>/?devices=<deviceid>"
      - "WATCHTOWER_NOTIFICATION_TEMPLATE={{range .}}{{.Time.Format \"2006-01-02 15:04:05\"}} ({{.Level}}): {{.Message}}{{println}}{{end}}"
    command: --interval 86400 --cleanup --debug
    restart: unless-stopped
```

I'm not sure if this is a feature or a bug, I wanted to understand why watchtower always reports  "_Could not do a head request, falling back to regular pull._" and maybe get rid of it.

This is a detailed log with `--debug` enabled (remark: reduced interval to 1/2 day for faster message trigger):
<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

```
time="2021-04-02T11:55:32Z" level=debug msg="Watchtower HTTP API skipped."
time="2021-04-02T11:55:32Z" level=info msg="Watchtower v0.0.0-unknown\nUsing notifications: pushover\nChecking all containers (except explicitly disabled with label)\nScheduling first run: 2021-04-02 23:55:32 +0000 UTC\nNote that the first check will be performed in 11 hours, 59 minutes, 59 seconds"

time="2021-04-02T23:55:32Z" level=debug msg="Checking containers for updated images"
time="2021-04-02T23:55:32Z" level=debug msg="Retrieving running containers"
time="2021-04-02T23:55:42Z" level=debug msg="Trying to load authentication credentials." container=/ct-smart-home_watchtower_1 image="containrrr/watchtower:latest"
time="2021-04-02T23:55:42Z" level=debug msg="No credentials for containrrr found" config_file=/config.json
time="2021-04-02T23:55:42Z" level=debug msg="Got image name: containrrr/watchtower:latest"
time="2021-04-02T23:55:42Z" level=debug msg="Checking if pull is needed" container=/ct-smart-home_watchtower_1 image="containrrr/watchtower:latest"
time="2021-04-02T23:55:42Z" level=debug msg="Building challenge URL" URL="https://index.docker.io/v2/"
time="2021-04-02T23:55:42Z" level=warning msg="Could not do a head request, falling back to regular pull." container=/ct-smart-home_watchtower_1 image="containrrr/watchtower:latest"
time="2021-04-02T23:55:42Z" level=debug msg="Reason: Get \"https://index.docker.io/v2/\": dial tcp: lookup index.docker.io on 127.0.0.11:53: no such host"
time="2021-04-02T23:55:42Z" level=debug msg="Pulling image" container=/ct-smart-home_watchtower_1 image="containrrr/watchtower:latest"

time="2021-04-02T23:55:48Z" level=debug msg="No new images found for /ct-smart-home_watchtower_1"
time="2021-04-02T23:55:48Z" level=debug msg="Trying to load authentication credentials." container=/ct-smart-home_mqtt_1 image="eclipse-mosquitto:latest"
time="2021-04-02T23:55:48Z" level=debug msg="No credentials for eclipse-mosquitto:latest found" config_file=/config.json
time="2021-04-02T23:55:48Z" level=debug msg="Got image name: eclipse-mosquitto:latest"
time="2021-04-02T23:55:48Z" level=debug msg="Checking if pull is needed" container=/ct-smart-home_mqtt_1 image="eclipse-mosquitto:latest"
time="2021-04-02T23:55:48Z" level=debug msg="Building challenge URL" URL="https://index.docker.io/v2/"
time="2021-04-02T23:55:48Z" level=debug msg="Got response to challenge request" header="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\"" status="401 Unauthorized"
time="2021-04-02T23:55:48Z" level=debug msg="Checking challenge header content" realm="https://auth.docker.io/token" service=registry.docker.io
time="2021-04-02T23:55:48Z" level=debug msg="Setting scope for auth token" image=eclipse-mosquitto scope="repository:library/eclipse-mosquitto:pull"
time="2021-04-02T23:55:48Z" level=debug msg="No credentials found."
time="2021-04-02T23:55:49Z" level=debug msg="Parsing image ref" host=index.docker.io image=eclipse-mosquitto normalized="docker.io/library/eclipse-mosquitto:latest" tag=latest
time="2021-04-02T23:55:49Z" level=debug msg="Doing a HEAD request to fetch a digest" url="https://index.docker.io/v2/library/eclipse-mosquitto/manifests/latest"
time="2021-04-02T23:55:50Z" level=debug msg="Found a remote digest to compare with" remote="sha256:1eb993a7dc3e7a7c10deabe5a45fd3990038d66e7060c9971f3833535092027d"
time="2021-04-02T23:55:50Z" level=debug msg=Comparing local="sha256:1eb993a7dc3e7a7c10deabe5a45fd3990038d66e7060c9971f3833535092027d" remote="sha256:1eb993a7dc3e7a7c10deabe5a45fd3990038d66e7060c9971f3833535092027d"
time="2021-04-02T23:55:50Z" level=debug msg="Found a match"
time="2021-04-02T23:55:50Z" level=debug msg="No pull needed. Skipping image."
time="2021-04-02T23:55:50Z" level=debug msg="No new images found for /ct-smart-home_mqtt_1"
time="2021-04-02T23:55:50Z" level=debug msg="Trying to load authentication credentials." container=/ct-smart-home_homebridge_1 image="oznu/homebridge:raspberry-pi"
time="2021-04-02T23:55:50Z" level=debug msg="No credentials for oznu found" config_file=/config.json
time="2021-04-02T23:55:50Z" level=debug msg="Got image name: oznu/homebridge:raspberry-pi"
time="2021-04-02T23:55:50Z" level=debug msg="Checking if pull is needed" container=/ct-smart-home_homebridge_1 image="oznu/homebridge:raspberry-pi"
time="2021-04-02T23:55:50Z" level=debug msg="Building challenge URL" URL="https://index.docker.io/v2/"
time="2021-04-02T23:55:51Z" level=debug msg="Got response to challenge request" header="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\"" status="401 Unauthorized"
time="2021-04-02T23:55:51Z" level=debug msg="Checking challenge header content" realm="https://auth.docker.io/token" service=registry.docker.io
time="2021-04-02T23:55:51Z" level=debug msg="Setting scope for auth token" image=oznu/homebridge scope="repository:oznu/homebridge:pull"
time="2021-04-02T23:55:51Z" level=debug msg="No credentials found."
time="2021-04-02T23:55:51Z" level=debug msg="Parsing image ref" host=index.docker.io image=oznu/homebridge normalized="docker.io/oznu/homebridge:raspberry-pi" tag=raspberry-pi
time="2021-04-02T23:55:51Z" level=debug msg="Doing a HEAD request to fetch a digest" url="https://index.docker.io/v2/oznu/homebridge/manifests/raspberry-pi"
time="2021-04-02T23:55:52Z" level=debug msg="Found a remote digest to compare with" remote="sha256:7eb5dd29ac3ae654c674ebc8a6cbd0a3f77d20580027f12c66c145e89181a003"
time="2021-04-02T23:55:52Z" level=debug msg=Comparing local="sha256:7eb5dd29ac3ae654c674ebc8a6cbd0a3f77d20580027f12c66c145e89181a003" remote="sha256:7eb5dd29ac3ae654c674ebc8a6cbd0a3f77d20580027f12c66c145e89181a003"
time="2021-04-02T23:55:52Z" level=debug msg="Found a match"
time="2021-04-02T23:55:52Z" level=debug msg="No pull needed. Skipping image."
time="2021-04-02T23:55:52Z" level=debug msg="No new images found for /ct-smart-home_homebridge_1"
time="2021-04-02T23:55:52Z" level=debug msg="Trying to load authentication credentials." container=/ntopng_redis_1 image="redis:alpine"
time="2021-04-02T23:55:52Z" level=debug msg="No credentials for redis:alpine found" config_file=/config.json
time="2021-04-02T23:55:52Z" level=debug msg="Got image name: redis:alpine"
time="2021-04-02T23:55:52Z" level=debug msg="Checking if pull is needed" container=/ntopng_redis_1 image="redis:alpine"
time="2021-04-02T23:55:52Z" level=debug msg="Building challenge URL" URL="https://index.docker.io/v2/"
time="2021-04-02T23:55:52Z" level=debug msg="Got response to challenge request" header="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\"" status="401 Unauthorized"
time="2021-04-02T23:55:52Z" level=debug msg="Checking challenge header content" realm="https://auth.docker.io/token" service=registry.docker.io
time="2021-04-02T23:55:52Z" level=debug msg="Setting scope for auth token" image=redis scope="repository:library/redis:pull"
time="2021-04-02T23:55:52Z" level=debug msg="No credentials found."
time="2021-04-02T23:55:52Z" level=debug msg="Parsing image ref" host=index.docker.io image=redis normalized="docker.io/library/redis:alpine" tag=alpine
time="2021-04-02T23:55:52Z" level=debug msg="Doing a HEAD request to fetch a digest" url="https://index.docker.io/v2/library/redis/manifests/alpine"
time="2021-04-02T23:55:53Z" level=debug msg="Found a remote digest to compare with" remote="sha256:142f857eb675a6a817dff1ae4d2138fc0228db596db2849ad1c38023a9dea7a4"
time="2021-04-02T23:55:53Z" level=debug msg=Comparing local="sha256:5c0374e9d2af14c0fb5cf0406d6fe74220998f7ec0250de33344d8e2a3b46305" remote="sha256:142f857eb675a6a817dff1ae4d2138fc0228db596db2849ad1c38023a9dea7a4"
time="2021-04-02T23:55:53Z" level=debug msg="Digests did not match, doing a pull."
time="2021-04-02T23:55:53Z" level=debug msg="Pulling image" container=/ntopng_redis_1 image="redis:alpine"
time="2021-04-02T23:56:05Z" level=info msg="Found new redis:alpine image (sha256:7d4711e7aff340e7a9449631c038a272fba958474dd5deab1e290d6ad4f8561c)"
time="2021-04-02T23:56:05Z" level=debug msg="Trying to load authentication credentials." container=/portainer image="portainer/portainer-ce:latest"
time="2021-04-02T23:56:05Z" level=debug msg="No credentials for portainer found" config_file=/config.json
time="2021-04-02T23:56:05Z" level=debug msg="Got image name: portainer/portainer-ce:latest"
time="2021-04-02T23:56:05Z" level=debug msg="Checking if pull is needed" container=/portainer image="portainer/portainer-ce:latest"
time="2021-04-02T23:56:05Z" level=debug msg="Building challenge URL" URL="https://index.docker.io/v2/"
time="2021-04-02T23:56:06Z" level=debug msg="Got response to challenge request" header="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\"" status="401 Unauthorized"
time="2021-04-02T23:56:06Z" level=debug msg="Checking challenge header content" realm="https://auth.docker.io/token" service=registry.docker.io
time="2021-04-02T23:56:06Z" level=debug msg="Setting scope for auth token" image=portainer/portainer-ce scope="repository:portainer/portainer-ce:pull"
time="2021-04-02T23:56:06Z" level=debug msg="No credentials found."
time="2021-04-02T23:56:06Z" level=debug msg="Parsing image ref" host=index.docker.io image=portainer/portainer-ce normalized="docker.io/portainer/portainer-ce:latest" tag=latest
time="2021-04-02T23:56:06Z" level=debug msg="Doing a HEAD request to fetch a digest" url="https://index.docker.io/v2/portainer/portainer-ce/manifests/latest"
time="2021-04-02T23:56:07Z" level=debug msg="Found a remote digest to compare with" remote="sha256:5064d8414091c175c55ef6f8744da1210819388c2136273b4607a629b7d93358"
time="2021-04-02T23:56:07Z" level=debug msg=Comparing local="sha256:5064d8414091c175c55ef6f8744da1210819388c2136273b4607a629b7d93358" remote="sha256:5064d8414091c175c55ef6f8744da1210819388c2136273b4607a629b7d93358"
time="2021-04-02T23:56:07Z" level=debug msg="Found a match"
time="2021-04-02T23:56:07Z" level=debug msg="No pull needed. Skipping image."
time="2021-04-02T23:56:07Z" level=debug msg="No new images found for /portainer"
time="2021-04-02T23:56:07Z" level=debug msg="Trying to load authentication credentials." container=/fhem_fhem_1 image="fhem/fhem:dev"
time="2021-04-02T23:56:07Z" level=debug msg="No credentials for fhem found" config_file=/config.json
time="2021-04-02T23:56:07Z" level=debug msg="Got image name: fhem/fhem:dev"
time="2021-04-02T23:56:07Z" level=debug msg="Checking if pull is needed" container=/fhem_fhem_1 image="fhem/fhem:dev"
time="2021-04-02T23:56:07Z" level=debug msg="Building challenge URL" URL="https://index.docker.io/v2/"
time="2021-04-02T23:56:08Z" level=debug msg="Got response to challenge request" header="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\"" status="401 Unauthorized"
time="2021-04-02T23:56:08Z" level=debug msg="Checking challenge header content" realm="https://auth.docker.io/token" service=registry.docker.io
time="2021-04-02T23:56:08Z" level=debug msg="Setting scope for auth token" image=fhem/fhem scope="repository:fhem/fhem:pull"
time="2021-04-02T23:56:08Z" level=debug msg="No credentials found."
time="2021-04-02T23:56:08Z" level=debug msg="Parsing image ref" host=index.docker.io image=fhem/fhem normalized="docker.io/fhem/fhem:dev" tag=dev
time="2021-04-02T23:56:08Z" level=debug msg="Doing a HEAD request to fetch a digest" url="https://index.docker.io/v2/fhem/fhem/manifests/dev"
time="2021-04-02T23:56:09Z" level=debug msg="Found a remote digest to compare with" remote="sha256:3ba0e75d4f72da06dfd55fdb841bdb92fa495884b596bcdf33e77edc5d08c50d"
time="2021-04-02T23:56:09Z" level=debug msg=Comparing local="sha256:3ba0e75d4f72da06dfd55fdb841bdb92fa495884b596bcdf33e77edc5d08c50d" remote="sha256:3ba0e75d4f72da06dfd55fdb841bdb92fa495884b596bcdf33e77edc5d08c50d"
time="2021-04-02T23:56:09Z" level=debug msg="Found a match"
time="2021-04-02T23:56:09Z" level=debug msg="No pull needed. Skipping image."
time="2021-04-02T23:56:09Z" level=debug msg="No new images found for /fhem_fhem_1"
time="2021-04-02T23:56:09Z" level=debug msg="This is the watchtower container /ct-smart-home_watchtower_1"
time="2021-04-02T23:56:09Z" level=info msg="Stopping /ntopng_redis_1 (11ebf206e1e20209ef279014287827a3168b494e69d305a64e888c912002e178) with SIGTERM"
time="2021-04-02T23:56:19Z" level=debug msg="Removing container 11ebf206e1e20209ef279014287827a3168b494e69d305a64e888c912002e178"
time="2021-04-02T23:56:19Z" level=info msg="Creating /ntopng_redis_1"
time="2021-04-02T23:56:28Z" level=debug msg="Starting container /ntopng_redis_1 (c2cb77c2f564a7a5fa9e117f563ac72bdd1678ec581208aaebf5308c9821b42e)"
time="2021-04-02T23:56:29Z" level=info msg="Removing image sha256:1c4b29047edba25e05314412e2f86c70ccccb1987685e45a36fb37c6156f130c"
time="2021-04-02T23:56:29Z" level=debug msg="Scheduled next run: 2021-04-03 11:55:32 +0000 UTC"
```
</details>

In my case I'm using the [Pushover Service](https://pushover.net) to get notification, but I think this is not necessary to reproduce the message. The message also appears in the logs above. 

The pushover message does only report (info) messages, right ?

```
Docker:
2021-04-02 23:55:42 (warning): Could not do a head request, falling back to regular pull.
2021-04-02 23:56:05 (info): Found new redis:alpine image (sha256:7d4711e7aff340e7a9449631c038a272fba958474dd5deab1e290d6ad4f8561c)
2021-04-02 23:56:09 (info): Stopping /ntopng_redis_1 (11ebf206e1e20209ef279014287827a3168b494e69d305a64e888c912002e178) with SIGTERM
2021-04-02 23:56:19 (info): Creating /ntopng_redis_1
2021-04-02 23:56:29 (info): Removing image sha256:1c4b29047edba25e05314412e2f86c70ccccb1987685e45a36fb37c6156f130c

```

Note also, that a one-time request via
```
docker run --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower \
    --run-once \
    portainer
```
does not trigger that message.

**Comment by piksel** [comment]
It doesn't work the first time (2021-04-02T23:55:48Z), but it succeeds subsequent attempts (6 seconds later it works normally). The first one logs the reason:
```
Reason: Get "https://index.docker.io/v2/": dial tcp: lookup index.docker.io on 127.0.0.11:53: no such host
```
Which meant that your local DNS (probably `systemd-resolved`) couldn't look up the address. Perhaps there were some internet issues?
If this happens consistently once on every run, there is probably a bug somewhere, but the question is where...
Perhaps it's something that goes in to power-save mode or similar, and doesn't have time to fully restore the connection before the first check?

**Comment by DannyBoyKN** [comment]
Mmmmh .. interesting !
I have Phiole natively running on the same Pi using stubby and dnscrypt-proxy as resolvers, but they're configured on 127.0.2.2:10053 and 127.0.2.3:10053 on the host ...
The question is why watchtower (container) is trying over 127.0.0.11:53 ? Of course, there's no DNS.
I'll continue to observe ... 

Just happened again
```
time="2021-04-03T11:55:32Z" level=debug msg="Checking if pull is needed" container=/ct-smart-home_watchtower_1 image="containrrr/watchtower:latest"
time="2021-04-03T11:55:32Z" level=debug msg="Building challenge URL" URL="https://index.docker.io/v2/"
time="2021-04-03T11:55:32Z" level=warning msg="Could not do a head request, falling back to regular pull." container=/ct-smart-home_watchtower_1 image="containrrr/watchtower:latest"
time="2021-04-03T11:55:32Z" level=debug msg="Reason: Get \"https://index.docker.io/v2/\": dial tcp: lookup index.docker.io on 127.0.0.11:53: no such host"
```

**Comment by DannyBoyKN** [comment]
I investigated a bit more on that warning and found this on [official docker documentation](https://docs.docker.com/config/containers/container-networking/):

> **DNS services**
> By default, a container inherits the DNS settings of the host, as defined in the `/etc/resolv.conf` configuration file. Containers that use the default bridge network get a copy of this file, whereas containers that use a custom network use Docker’s embedded DNS server, which forwards external DNS lookups to the DNS servers configured on the host.

127.0.0.11 is the _Docker’s embedded DNS server_ !!! And DNS lookups are forwarded to DNS servers configured on the host. Basically everything's fine and watchtower seems still to be working despite that confusing warning message.

**Comment by piksel** [comment]
Yeah, the only "problem" is that it will consume one of your rate limited pulls from docker hub once on every check. Since that is only once every 86400s it should be fine 😁.
You can add the `--warn-on-head-failure never` argument if you don't want to get any more warnings for it (as of v1.3.0).

As for actually solving the issue, it might have been solved by itself in v1.3.0 since we added some more of the default http client options, but otherwise it is kind of hard for watchtower to do anything about it.

Let us know if you want any further assistance in investigating this, or feel free to close the issue.

**Comment by DannyBoyKN** [comment]
With `--warn-on-head-failure never` it works now as before, no 'spam' logs, but updates as available.

Although I set the period to 1 day (`--interval 86400`) i still do not understand why 'head request" does not work, so 'falling back to regular pull'. What's actually the difference ?

**Comment by simonaronsson** [comment]
Yeah, that actually sounds like a bug. Is it for all containers or only selected ones? Would be great if we'd be able to reproduce it on our machines.

**Comment by DannyBoyKN** [comment]
You mean more than in the above log ?
The update request / verification started with "Checking if pull is needed" for the watchtower container, but successive checks did succeed, for both when no updates and updates were discovered.
What else can I try ?

**Comment by piksel** [comment]
The HEAD requests are just a little more efficient way of checking for changes. In your case, it fails to do it for the first of the containers, and then uses the fallback method of asking Docker to pull the image. There is almost no gain in trying to fix it, perhaps a couple of bytes less bandwidth per day...  
If you wanted to check once every 5 minutes, then it *might* become an issue, but it would probably come down to OS/environment configuration.

**Comment by simonaronsson** [comment]
> The update request / verification started with "Checking if pull is needed" for the watchtower container, but successive checks did succeed, for both when no updates and updates were discovered.

Oh, in that case, there's nothing more to do here, so I'm closing this issue. 🎉
